### PR TITLE
Updates deprecated numpy conventions

### PR DESCRIPTION
**Pull request by arrrrrmin**
Fixes some older numpy conventions like np.int or [np.asscalar](https://numpy.org/doc/1.22/reference/generated/numpy.asscalar.html). 
Used numpy version: `1.24.1`

### CODE REVIEW

**Comment by mdbartos** [comment]
Thanks for this. The old CI based on Travis is no longer working, and will need to be re-implemented in Github actions. After that, I can pull in this request.

(Unless someone else with access wants to help enable CI via Github actions. Any interest @abhiramm7 😛?)

**Comment by abhiramm7** [comment]
Haha, can do! @mdbartos

**Comment by arrrrrmin** [comment]
Ok but for 
```yaml
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
```
I need to change the PR\`s target to `kLabUM:master`, are you fine with merging into `master`?

**Comment by mdbartos** [comment]
I can see that the tests have passed on your branch, so I am going to merge in and see if they pass here. I will follow up if I find any issues.

Thanks!
MDB

**Pull request merged**
