### PR TITLE
Added random state to the constructor of RCTree

### PR DESCRIPTION
**Pull request by NikosGavalas**
Added an optional parameter to the constructor of RCTree, called "random_state". It can be int, an np.random.RandomState instance of None (default), like in all sklearn modules.

This allows for optional generation of the same tree, if the same seed (int or RandomState) is provided, which is incredibly useful (for writing tests etc.)

### CODE REVIEW

**Comment by mdbartos** [comment]
Hi Nick,

Thanks for your contribution. Could you increase test coverage so that it's the same as it was before?

Thanks,
MDB

**Comment by mdbartos** [comment]
Also, can you add a description of the random_state argument to the docstring?

**Comment by NikosGavalas** [comment]
Hello,

I did the necessary changes.

Thanks,
Nick

**Comment by mdbartos** [comment]
Looks good to me!

**Pull request merged**
